export const voiceConfig = [
  {
    name: "Abeo",
    voice: "en-NG-AbeoNeural",
    gender: "male",
    country: "Nigeria",
  },
  {
    name: "Jenny",
    voice: "en-US-JennyNeural",
    gender: "female",
    country: "United States",
  },
  {
    name: "Asilia",
    voice: "en-KE-AsiliaNeural",
    gender: "female",
    country: "Kenya",
  },
  {
    name: "Denise",
    voice: "fr-FR-DeniseNeural",
    gender: "female",
    country: "France",
  },
  {
    name: "Sonia",
    voice: "en-GB-SoniaNeural",
    gender: "female",
    country: "United Kingdom",
  },
  {
    name: "Jason",
    voice: "en-US-JasonNeural",
    gender: "male",
    country: "United States",
  },
  {
    name: "Ezinne",
    voice: "en-NG-EzinneNeural",
    gender: "female",
    country: "Nigeria",
  },
  {
    name: "Henri",
    voice: "fr-FR-HenriNeural",
    gender: "male",
    country: "France",
  },
  {
    name: "Clara",
    voice: "pt-BR-ClaraNeural",
    gender: "female",
    country: "Brazil",
  },
  {
    name: "Miguel",
    voice: "es-ES-MiguelNeural",
    gender: "male",
    country: "Spain",
  },
  {
    name: "Xiaoyu",
    voice: "zh-CN-XiaoyuNeural",
    gender: "female",
    country: "China",
  },
  {
    name: "Nanami",
    voice: "ja-JP-NanamiNeural",
    gender: "female",
    country: "Japan",
  },
  {
    name: "Conrad",
    voice: "de-DE-ConradNeural",
    gender: "male",
    country: "Germany",
  },
  {
    name: "Diego",
    voice: "it-IT-DiegoNeural",
    gender: "male",
    country: "Italy",
  },
  {
    name: "Colette",
    voice: "nl-NL-ColetteNeural",
    gender: "female",
    country: "Netherlands",
  },
];
