export const voiceConfig = [
  {
    name: "Abeo",
    voice: "en-NG-AbeoNeural",
    gender: "male",
    country: "Nigeria",
  },
  {
    name: "Jenny",
    voice: "en-US-JennyNeural",
    gender: "female",
    country: "United States",
  },
  {
    name: "Asilia",
    voice: "en-KE-AsiliaNeural",
    gender: "female",
    country: "Kenya",
  },
  {
    name: "Denise",
    voice: "fr-FR-DeniseNeural",
    gender: "female",
    country: "France",
  },
  {
    name: "Sonia",
    voice: "en-GB-SoniaNeural",
    gender: "female",
    country: "United Kingdom",
  },
  {
    name: "Jason",
    voice: "en-US-JasonNeural",
    gender: "male",
    country: "United States",
  },
  {
    name: "Ezinne",
    voice: "en-NG-EzinneNeural",
    gender: "female",
    country: "Nigeria",
  },
  {
    name: "Henri",
    voice: "fr-FR-HenriNeural",
    gender: "male",
    country: "France",
  },
  {
    name: "Clara",
    voice: "pt-BR-ClaraNatural",
    gender: "female",
    country: "Brazil",
  },
  {
    name: "Miguel",
    voice: "es-ES-MiguelNeural",
    gender: "male",
    country: "Spain",
  },
  {
    name: "Xiaomei",
    voice: "zh-CN-XiaomeiNeural",
    gender: "female",
    country: "China",
  },
  {
    name: "Yuki",
    voice: "ja-JP-YukiNeural",
    gender: "female",
    country: "Japan",
  },
  {
    name: "Klaus",
    voice: "de-DE-KlausNeural",
    gender: "male",
    country: "Germany",
  },
  {
    name: "Pietro",
    voice: "it-IT-PietroNeural",
    gender: "male",
    country: "Italy",
  },
  {
    name: "Sofie",
    voice: "nl-NL-SofieNeural",
    gender: "female",
    country: "Netherlands",
  },
];
